// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcBG4Nrz_2RrvVc9LxRTAvxLRNQTqH-yE',
    appId: '1:105949843153:android:b9e82209aac9043feffff0',
    messagingSenderId: '105949843153',
    projectId: 'healthtrack-f8d37',
    storageBucket: 'healthtrack-f8d37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxd_2BJu0tlnCtli1GQPKd9ZKkpkjY0GM',
    appId: '1:105949843153:ios:cefe14a8dc5e9b9beffff0',
    messagingSenderId: '105949843153',
    projectId: 'healthtrack-f8d37',
    storageBucket: 'healthtrack-f8d37.appspot.com',
    iosClientId:
        '105949843153-vfp79b4iv2v35s8ghe3f4d4gd337iusp.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicalProject',
  );
}
